name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create config.ini
      run: |
        echo "[firebase]" >> config.ini
        echo "project_id=${{ secrets.FIREBASE_PROJECT_ID }}" >> config.ini
        echo "api_key=${{ secrets.FIREBASE_API_KEY }}" >> config.ini
        echo "database_url=${{ secrets.FIREBASE_DATABASE_URL }}" >> config.ini
        echo "auth_domain=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> config.ini
    - name: Run tests
      env:
        GOOGLE_APPLICATION_CREDENTIALS: service-account.json
        FIREBASE_DATABASE_URL: "${{ secrets.FIREBASE_DATABASE_URL }}"
      run: |
        echo "Running tests with Firebase configuration:"
        echo "Database URL: \"$FIREBASE_DATABASE_URL\""
        echo "Verifying config.ini content:"
        cat config.ini
        echo "\nVerifying service-account.json exists:"
        ls -l service-account.json
        echo "\nVerifying environment variables:"
        env | grep FIREBASE
        echo "\nRunning tests with debug output:"
        python -m pytest -v
    - name: Cleanup credentials
      if: always()
      run: |
        rm -f service-account.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production..."